version: '2'

services:

  database:
    image: postgres
    environment:
      - POSTGRES_DB=user_space
      - POSTGRES_USER=postgres
      - DB_USER=postgres
      - DB_PASS=qwertz
    volumes:
      - "/var/lib/postgresql/data"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - database
